### ISSUE TITLE
add reduxToolkit slice testing

### ISSUE THREAD

**Issue by jamiehaywood** [mrdulin/jest-v26-codelab#1]
hi, 

First of all, I want to say how much of a fan I am of your v24 & 26 codelabs, Extremely helpful for learning & looking at different approaches to testing in Express & React. Do you have a `buy me a coffee` link or alternative?

Have you got any testing examples for testing ReduxToolkit slices, associated reducers & thunks? I would be very interested to see your take on how to test these.

cheers & thanks again for your awesome repos!

**Comment by mrdulin** [comment]
Thanks. I am very happy that my test code example helps you. Buy me a coffee link here: https://opencollective.com/slideshowp2#backers

I have used Redux-Toolkit for several months, and I am very interested in how to write test code. If you have problems, you can ask questions on Stackoverflow, we study together.
